name: Main Branch CI

on:
  push:
    branches:
      - main

jobs:
  call-qa-workflow:
    uses: ./.github/workflows/reusable-qa.yml
    secrets: inherit

  # run-semantic-release:
  #   needs: call-qa-workflow
  #   runs-on: ubuntu-latest
  #   outputs:
  #     new_release_version: ${{ steps.semantic_release.outputs.new_release_version }}
  #   steps:
  #     - name: Setup Environment
  #       uses: ./.github/actions/setup-environment
  #
  #     - name: Install Bun
  #       run: bun install
  #
  #     - name: Run Semantic Release
  #       id: semantic_release
  #       run: bun run release
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    needs: call-qa-workflow
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - name: Setup Environment
        uses: ./.github/actions/setup-environment

      - name: Install Bun
        run: bun install

      - name: Build and Release Tauri Application
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: app-build-${{ github.run_number }}
          releaseName: 'App build ${{ github.run_number }}'
          releaseBody: 'Automated macOS build. See the assets to download this version and install.'
          releaseDraft: false
          prerelease: false
          args: --bundles dmg